### ISSUE TITLE
добавить setLocalFileDetector при инициализации RemoteWebDriver

### ISSUE THREAD

**Issue by Ostryak** [sbtqa/page-factory-2#131]
для того, чтобы заливка файлов работала на селениум хабе (моон, селеноид и т.п.) необходимо настроить FileDetector

класс - WebDriverService
метод createRemoteWebDriver 

добавить строчку 
remoteWebDriver.setFileDetector(new LocalFileDetector());

в создание не ремоут драйвера не нужно добавлять этот код

**Comment by clicman** [comment]
Closed via #135
