### ISSUE TITLE
Проблемы с запуском Android тестов

### ISSUE THREAD

**Issue by insomnia77** [sbtqa/page-factory-2#158]
Добрый день.
 Пример сценария лежит внутри page-factory-2 (mobile-plugin pagefactory.mobile CucumberTest)

При попытке запуска примера вылетает ошибка:
 cucumber.runtime.DuplicateStepDefinitionException: Duplicate step definitions in ru.sbtqa.tag.stepdefs.ru.CoreStepDefs.fill(String,String) in .../page_factory-2/page-factory-core/target/classes/ and ru.sbtqa.tag.stepdefs.ru.CoreStepDefs.fill(String,String) in .../page_factory-2/page-factory-core/target/classes/ 

 Возможно ли вынести пример с мобильными тестами в page-factory-2-example b lj,fdbnm в пример использование блоков и фрагментов?

Планируется ли делать поддержку IOS?

**Comment by clicman** [comment]
Привет!
Да, для Android сделаем пример. По поводу iOS: у нас ни у одного разработчика нет мака поэтому, к сожалению мы не можем оперативно сделать поддержу iOS.  Если у вас есть возможность нам помочь с поддержкой iOS, будем благодарны. Прошу написать мне в личку на viktor.sidochenko@gmail.com  и мы обсудим детали.

**Comment by clicman** [comment]
@insomnia77 track the https://github.com/sbtqa/page-factory-2/pull/164 activity.

**Comment by clicman** [comment]
Выпущена версия 10.0.0
Поддержка iOs будет проверена в ближайшее время.
