### ISSUE TITLE
Проблема при использовании Connector и data.type=properties

### ISSUE THREAD

**Issue by Sergo101010100** [sbtqa/page-factory-2#184]
qa-ulits. Версия 1.4.0
pf2. Версия 10.1.3
 
В конструкторе класса Connector стоит `Props.get(name+".url")`, который по дефолту тянет из application.properties. Если использовать data.type=properties, то параметры подключения к БД лежат в другом properties-файле (для разных конфигураций) и Connector не работает.

Я так понимаю актуально для использование любого data.type

**Comment by kosteman** [comment]
исправлено в https://github.com/sbtqa/page-factory-2/releases/tag/11.0.0

**Comment by Sergo101010100** [comment]
Что-то очень интересно исправили. Теперь этого класса вообще нет :) Огонь исправили

**Comment by clicman** [comment]
Его перенесли в пф2. См. Release notes.

**Comment by Sergo101010100** [comment]
Да, но при этом использовать его с data.type как я понял не получится. 

Класс Connector ` DriverManager.getConnection(Configuration.create(names).getDbUrl())`.

Класс `ru.sbtqa.tag.pagefactory.properties.Configuration` и там в явном виде стоит
`@Key("db.${name}.url")
    String getDbUrl();`

И если я правильно понимаю, то он будет тянуть из application.properties этот параметр, а не из указанного data.type.  Поправьте если ошибаюсь.

**Comment by clicman** [comment]
@kosteman посмотри.

**Comment by kosteman** [comment]
Как именно используется Connector? как выглядить фича, степдефы и *.properties файлы?

Есть вариант использовать другой конструктор Connector(java.sql.Connection)
