### ISSUE TITLE
Decide how to reflect to nullable value

### ISSUE THREAD

**Issue by clicman** [sbtqa/page-factory-2#190]
We need to supply a "", null and removed values.
For example, we have the following body template:

    {
      "message": "${message}"
    }

Now if pass the empty value to a data table, the template will generate as is.
But we should support an empty string value, null and remove it from the template at all:

    {"message": ""}

    {"message": null}

    {}

So we need to think about how to do it.

My suggestion is:
1. pass ""
2. null
3. *an empty input*

**Comment by kosteman** [comment]
Задано ли поле как 
`String message = null;`
или не определено как
`String message;`
для рефлексии не будет никакой разницы и оно будет считаться null.

Моё предложение:
поддерживать 
`{"message": ""}`
`{"message": null}`

Удаление параметра по пустому(что считать пустым) полю считаю не тривиальным и тонким местом.
