### ISSUE TITLE
Rest Endpoint called twice with send() always gets params from the first one.

### ISSUE THREAD

**Issue by clicman** [sbtqa/page-factory-2#194]
Ho to reproduce:
    
    ApiSteps.getInstance().fill(SomeEndpointEntry.class).add(HEADER, "Authorization", "1").send();
    ApiSteps.getInstance().fill(SomeEndpointEntry.class).add(HEADER, "Authorization", "2").send();

Problems:
1. Method [send()](https://github.com/sbtqa/page-factory-2/blob/f493c06c7dda233e71b62f0a3ce5210eebc78ac9/plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/junit/ApiStepsImpl.java#L44) always executes the first endpoint in the list. 
2. Endpoints aren't cleared between scenario outline examples.

**Comment by kosteman** [comment]
need example on case 2

**Comment by clicman** [comment]
verified
