### ISSUE TITLE
Найти аналог метода waitForElementGetEnabled

### ISSUE THREAD

**Issue by andriuha1987** [sbtqa/page-factory-2#196]
Подскажите в pf1 в классе DriverExtension был метод
public static void waitForElementGetEnabled(WebElement webElement, long timeout) throws WaitException {

Где найти его аналог в pf2.

Плюс подскажите актуальную ссылку, а то на эту выдает 404
1. По части миграции ui: большинство случаев описано здесь https://github.com/sbtqa/docs/wiki/PF-to-PF2-migration

**Comment by clicman** [comment]
Привет! 
Этот репозиторий был удален. И надо смотреть документацию на https://docs.sbtqa.ru

Теперь вся логика ожиданий находится в классе [Wait](https://github.com/sbtqa/page-factory-2/blob/master/page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/utils/Wait.java), все методы задокументированы.
