### ISSUE TITLE
There is no "isElementFocused" method in CoreStepDefs for "ru" package

### ISSUE THREAD

**Issue by andriuha1987** [sbtqa/page-factory-2#206]
В CoreStepDefs для пакета en имеется метод

@And("^element \"([^\"]*)\" is focused$")
public void isElementFocused(String element) {
    coreSteps.isElementFocused(element);
}

в пакете ru в CoreStepDefs он отсутствует. Версия 11.1.1

**Comment by kosteman** [comment]
isElementFocused добавлен в кг пакет.
! Прошу заметить, что isElementFocused не реализован  

```
    /**
     * Element is focused
     *
     * @param element element to focus on
     * @return Returns itself 
     */
    public T isElementFocused(String element) {
        LOG.warn("Note that isElementFocused method is still an empty!");
        return (T) this;
    }
```
