### ISSUE TITLE
incorrect reflection in 11.1.1

### ISSUE THREAD

**Issue by andriuha1987** [sbtqa/page-factory-2#209]
В продолжении https://github.com/sbtqa/page-factory-2/issues/199

Данное исправление сломало другие действия. Найден новый дефект.

Имеем шаг
@И("^(?:таблица|список|столбец) \"([^\"]+)\"\\s* \\((.*?)\\)$")
public void standard_action_5(String element, String action, List<String> elementName) throws NoSuchMethodException {
    Environment.getReflection().executeMethodByTitle(PageContext.getCurrentPage(), action, element, elementName);
}

Его мы вызываем напрямую из cucumber.
Проблема кроется в новом методе isArgumentsIdentical. А именно строчки
if (!methodParameters[index].getType().getName()
                    .equals(actionParameters[index].getClass().getName())) {
                return false;
            }

Потому что там в условии будут сравниваться.
java.util.Collections$UnmodifiableRandomAccessList
java.util.List
 
Сравнение не проходит.
 (UnmodifiableRandomAccessList это именно такую имплементацию List делает Cucumber)
Но по факту параметры идентичны и сработают.

**Comment by clicman** [comment]
@kosteman возмжно нам из assignableFrom только Object выкинуть(ну если это не сам Object), а остальное приведение типов считать валидным? @andriuha1987 какова вероятность иметь два экшена с перекастующимися типами?

**Comment by andriuha1987** [comment]
На нашем проекте, по сути из кукумбера на вход могут податься String и DataTable, который преобразуется или в List или Map, но только типа Unmodifiable

**Comment by clicman** [comment]
Нет, я имею ввиду такую ситуацию, когда у тебя рядом два метда - у одного в сигнатуре DataTable, а у другого Map?

**Comment by andriuha1987** [comment]
Боюсь ошибиться, но мне кажется в таком случае сам кукумбер выдаст ошибку о дупликате

**Comment by clicman** [comment]
прооверь плз, и сбда отпиши, если под рукой код.

пт, 29 мар. 2019 г. в 17:52, andriuha1987 <notifications@github.com>:

**Comment by andriuha1987** [comment]
Ок, пока кода нет под рукой, но через час   
 отпишусь

**Comment by andriuha1987** [comment]
Проверил, выдает DuplicateStepDefitionException

**Comment by clicman** [comment]
@kosteman подсмотри как в кукумбере это отруливается.

**Comment by andriuha1987** [comment]
Подскажите, когда планируется исправить данный дефект?
