### ISSUE TITLE
incorrect status test in allure

### ISSUE THREAD

**Issue by Sergo101010100** [sbtqa/page-factory-2#212]
При запуске тестов с нереализованными шагами - в Allure отображается статус кейса = Passed

![image](https://user-images.githubusercontent.com/48100063/55323066-b32e0800-5486-11e9-913b-5ce4c2730f96.png)

json allure
`{
  "uuid": "8abf1902-d197-4d78-885f-849c5a754058",
  "name": "Сценарий: 335 Проверка появления транзакции в RSA_UKO_EVENT",
  "children": [
    "e306cedd-32ab-4fec-84d8-61500bf80f1b"
  ],
  "befores": [
    {
      "name": "CoreStepDefs.preSetUp()",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116158044,
      "stop": 1554116158154
    },
    {
      "name": "CoreStepDefs.preSetUp()",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116158154,
      "stop": 1554116158154
    },
    {
      "name": "WebStepDefs.initWeb()",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116158154,
      "stop": 1554116159886
    },
    {
      "name": "WebStepDefs.initWeb()",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116159886,
      "stop": 1554116160498
    },
    {
      "name": "HtmlStepDefs.initHtml()",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116160498,
      "stop": 1554116161008
    },
    {
      "name": "HtmlStepDefs.initHtml()",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116161008,
      "stop": 1554116161008
    },
    {
      "name": "BeforeStepDefs.before(Scenario)",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "Время запуска теста: 2019-04-01T13:56:01.039",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1554116161054,
          "stop": 1554116161086
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1554116161008,
      "stop": 1554116161086
    },
    {
      "name": "BeforeStepDefs.integration()",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116161086,
      "stop": 1554116161086
    },
    {
      "name": "CoreStepDefs.setUp()",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116161086,
      "stop": 1554116161086
    },
    {
      "name": "CoreStepDefs.setUp()",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116161086,
      "stop": 1554116161086
    }
  ],
  "afters": [
    {
      "name": "WebStepDefs.disposeWeb()",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116166350,
      "stop": 1554116166350
    },
    {
      "name": "WebStepDefs.disposeWeb()",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116166350,
      "stop": 1554116166350
    },
    {
      "name": "CoreStepDefs.tearDown()",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116166350,
      "stop": 1554116166381
    },
    {
      "name": "CoreStepDefs.tearDown()",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116166381,
      "stop": 1554116166381
    },
    {
      "name": "AfterStepDefs.deleteAllCooke(Scenario)",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116166381,
      "stop": 1554116166381
    }
  ],
  "links": [],
  "start": 1554116157998,
  "stop": 1554116166381
}`
`{
  "name": "335 Проверка появления транзакции в RSA_UKO_EVENT",
  "status": "passed",
  "statusDetails": {
    "known": false,
    "muted": false,
    "flaky": false,
    "message": "TODO: implement me",
    "trace": "cucumber.api.PendingException: TODO: implement me\r\n\tat io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm.handlePickleStep(AllureCucumber2Jvm.java:340)\r\n\tat io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm.handleTestStepFinished(AllureCucumber2Jvm.java:220)\r\n\tat io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm$$Lambda$5/1610372241.receive(Unknown Source)\r\n\tat cucumber.runner.EventBus.send_aroundBody0(EventBus.java:28)\r\n\tat cucumber.runner.EventBus$AjcClosure1.run(EventBus.java:1)\r\n\tat org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:229)\r\n\tat ru.sbtqa.tag.pagefactory.aspects.CriticalStepCheckAspect.sendStepFinished(CriticalStepCheckAspect.java:122)\r\n\tat cucumber.runner.EventBus.send_aroundBody2(EventBus.java:25)\r\n\tat cucumber.runner.EventBus$AjcClosure3.run(EventBus.java:1)\r\n\tat org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)\r\n\tat ru.sbtqa.tag.pagefactory.aspects.StashAspect.sendStepFinished(StashAspect.java:86)\r\n\tat cucumber.runner.EventBus.send_aroundBody4(EventBus.java:25)\r\n\tat cucumber.runner.EventBus.send_aroundBody6(EventBus.java:25)\r\n\tat cucumber.runner.EventBus.send_aroundBody8(EventBus.java:25)\r\n\tat cucumber.runner.EventBus$AjcClosure9.run(EventBus.java:1)\r\n\tat org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)\r\n\tat ru.sbtqa.tag.pagefactory.aspects.report.ErrorHandlerAspect.sendStepFinished(ErrorHandlerAspect.java:29)\r\n\tat cucumber.runner.EventBus.send(EventBus.java:25)\r\n\tat cucumber.api.TestStep.run_aroundBody0(TestStep.java:90)\r\n\tat cucumber.api.TestStep$AjcClosure1.run(TestStep.java:1)\r\n\tat org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)\r\n\tat ru.sbtqa.tag.pagefactory.aspects.StashAspect.run(StashAspect.java:52)\r\n\tat cucumber.api.TestStep.run(TestStep.java:78)\r\n\tat cucumber.api.TestCase.run(TestCase.java:58)\r\n\tat cucumber.runner.Runner.runPickle(Runner.java:80)\r\n\tat cucumber.runtime.junit.PickleRunners$WithStepDescriptions.run(PickleRunners.java:95)\r\n\tat cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)\r\n\tat cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)\r\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\r\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\r\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\r\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\r\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\r\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\r\n\tat cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)\r\n\tat cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)\r\n\tat cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)\r\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\r\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\r\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\r\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\r\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\r\n\tat cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)\r\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\r\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)\r\n"
  },
  "stage": "finished",
  "steps": [
    {
      "name": "*  он ждет 5 секунд",
      "status": "passed",
      "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false
      },
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116161086,
      "stop": 1554116166319
    },
    {
      "name": "*  отправить через SOAP \"перевод частному лицу\" для клиента \"335\" без создания в БД",
      "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false,
        "message": "TODO: implement me",
        "trace": "cucumber.api.PendingException: TODO: implement me\r\n\tat io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm.handlePickleStep(AllureCucumber2Jvm.java:340)\r\n\tat io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm.handleTestStepFinished(AllureCucumber2Jvm.java:220)\r\n\tat io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm$$Lambda$5/1610372241.receive(Unknown Source)\r\n\tat cucumber.runner.EventBus.send_aroundBody0(EventBus.java:28)\r\n\tat cucumber.runner.EventBus$AjcClosure1.run(EventBus.java:1)\r\n\tat org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:229)\r\n\tat ru.sbtqa.tag.pagefactory.aspects.CriticalStepCheckAspect.sendStepFinished(CriticalStepCheckAspect.java:122)\r\n\tat cucumber.runner.EventBus.send_aroundBody2(EventBus.java:25)\r\n\tat cucumber.runner.EventBus$AjcClosure3.run(EventBus.java:1)\r\n\tat org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)\r\n\tat ru.sbtqa.tag.pagefactory.aspects.StashAspect.sendStepFinished(StashAspect.java:86)\r\n\tat cucumber.runner.EventBus.send_aroundBody4(EventBus.java:25)\r\n\tat cucumber.runner.EventBus.send_aroundBody6(EventBus.java:25)\r\n\tat cucumber.runner.EventBus.send_aroundBody8(EventBus.java:25)\r\n\tat cucumber.runner.EventBus$AjcClosure9.run(EventBus.java:1)\r\n\tat org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)\r\n\tat ru.sbtqa.tag.pagefactory.aspects.report.ErrorHandlerAspect.sendStepFinished(ErrorHandlerAspect.java:29)\r\n\tat cucumber.runner.EventBus.send(EventBus.java:25)\r\n\tat cucumber.api.TestStep.run_aroundBody0(TestStep.java:90)\r\n\tat cucumber.api.TestStep$AjcClosure1.run(TestStep.java:1)\r\n\tat org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)\r\n\tat ru.sbtqa.tag.pagefactory.aspects.StashAspect.run(StashAspect.java:52)\r\n\tat cucumber.api.TestStep.run(TestStep.java:78)\r\n\tat cucumber.api.TestCase.run(TestCase.java:58)\r\n\tat cucumber.runner.Runner.runPickle(Runner.java:80)\r\n\tat cucumber.runtime.junit.PickleRunners$WithStepDescriptions.run(PickleRunners.java:95)\r\n\tat cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)\r\n\tat cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)\r\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\r\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\r\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\r\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\r\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\r\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\r\n\tat cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)\r\n\tat cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)\r\n\tat cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)\r\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\r\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\r\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\r\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\r\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\r\n\tat cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)\r\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\r\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)\r\n"
      },
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116166334,
      "stop": 1554116166334
    },
    {
      "name": "*  проверить что последнее отправленное сообщение по клиенту \"335\" записалось в таблицу \"RSA_UKO_EVENT\"",
      "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false,
        "message": "TODO: implement me",
        "trace": "cucumber.api.PendingException: TODO: implement me\r\n\tat io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm.handlePickleStep(AllureCucumber2Jvm.java:340)\r\n\tat io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm.handleTestStepFinished(AllureCucumber2Jvm.java:220)\r\n\tat io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm$$Lambda$5/1610372241.receive(Unknown Source)\r\n\tat cucumber.runner.EventBus.send_aroundBody0(EventBus.java:28)\r\n\tat cucumber.runner.EventBus$AjcClosure1.run(EventBus.java:1)\r\n\tat org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:229)\r\n\tat ru.sbtqa.tag.pagefactory.aspects.CriticalStepCheckAspect.sendStepFinished(CriticalStepCheckAspect.java:122)\r\n\tat cucumber.runner.EventBus.send_aroundBody2(EventBus.java:25)\r\n\tat cucumber.runner.EventBus$AjcClosure3.run(EventBus.java:1)\r\n\tat org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)\r\n\tat ru.sbtqa.tag.pagefactory.aspects.StashAspect.sendStepFinished(StashAspect.java:86)\r\n\tat cucumber.runner.EventBus.send_aroundBody4(EventBus.java:25)\r\n\tat cucumber.runner.EventBus.send_aroundBody6(EventBus.java:25)\r\n\tat cucumber.runner.EventBus.send_aroundBody8(EventBus.java:25)\r\n\tat cucumber.runner.EventBus$AjcClosure9.run(EventBus.java:1)\r\n\tat org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)\r\n\tat ru.sbtqa.tag.pagefactory.aspects.report.ErrorHandlerAspect.sendStepFinished(ErrorHandlerAspect.java:29)\r\n\tat cucumber.runner.EventBus.send(EventBus.java:25)\r\n\tat cucumber.api.TestStep.run_aroundBody0(TestStep.java:90)\r\n\tat cucumber.api.TestStep$AjcClosure1.run(TestStep.java:1)\r\n\tat org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)\r\n\tat ru.sbtqa.tag.pagefactory.aspects.StashAspect.run(StashAspect.java:52)\r\n\tat cucumber.api.TestStep.run(TestStep.java:78)\r\n\tat cucumber.api.TestCase.run(TestCase.java:58)\r\n\tat cucumber.runner.Runner.runPickle(Runner.java:80)\r\n\tat cucumber.runtime.junit.PickleRunners$WithStepDescriptions.run(PickleRunners.java:95)\r\n\tat cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)\r\n\tat cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)\r\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\r\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\r\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\r\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\r\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\r\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\r\n\tat cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)\r\n\tat cucumber.api.junit.Cucumber.runChild(Cucumber.java:118)\r\n\tat cucumber.api.junit.Cucumber.runChild(Cucumber.java:56)\r\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\r\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\r\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\r\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\r\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\r\n\tat cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:127)\r\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\r\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)\r\n\tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)\r\n"
      },
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1554116166334,
      "stop": 1554116166334
    }
  ],
  "attachments": [],
  "parameters": [],
  "start": 1554116157998,
  "stop": 1554116166381,
  "uuid": "e306cedd-32ab-4fec-84d8-61500bf80f1b",
  "historyId": "aead762c179a053169e268a578c420f4",
  "fullName": "Smoke: 335 Проверка появления транзакции в RSA_UKO_EVENT",
  "labels": [
    {
      "name": "feature",
      "value": "Smoke"
    },
    {
      "name": "story",
      "value": "335 Проверка появления транзакции в RSA_UKO_EVENT"
    },
    {
      "name": "tag",
      "value": "335"
    },
    {
      "name": "tag",
      "value": "all"
    },
    {
      "name": "tag",
      "value": "ift"
    },
    {
      "name": "tag",
      "value": "data=$data"
    },
    {
      "name": "tag",
      "value": "integrationFL"
    },
    {
      "name": "host",
      "value": "DF-160816-KM01"
    },
    {
      "name": "thread",
      "value": "6948@DF-160816-KM01.main(1)"
    },
    {
      "name": "package",
      "value": "Smoke"
    },
    {
      "name": "suite",
      "value": "Smoke"
    },
    {
      "name": "testClass",
      "value": "335 Проверка появления транзакции в RSA_UKO_EVENT"
    },
    {
      "name": "framework",
      "value": "cucumber2jvm"
    },
    {
      "name": "language",
      "value": "java"
    }
  ],
  "links": []
}`

**Comment by clicman** [comment]
Это нормальное поведение. Я его в allure плагине реализовал в самом аллюре.

**Comment by Sergo101010100** [comment]
Есть сомнения по поводу нормальности такого поведения, ведь тест реализован не корректно. Это скорее ошибка тест. Или какая-то другая логика тут?

**Comment by clicman** [comment]
Нет, это корректно по самому кукумберу. То есть, там pending шаги в конце
считаются не критичными для сценария.

пн, 1 апр. 2019 г. в 18:18, Sergo101010100 <notifications@github.com>:
