### ISSUE TITLE
Действие "нажимает кнопку" не находит

### ISSUE THREAD

**Issue by NasakB** [sbtqa/page-factory-2#225]
Не находит CoreStepDefs.click

ru.sbtqa.tag.pagefactory html-plugin 11.1.1
лог:
* пользователь (нажимает кнопку) "Esc" # CoreStepDefs.action(String,String)
ru.sbtqa.tag.pagefactory.exceptions.NoSuchActionError: There is no 'нажимает кнопку' method on 'class ru.sbt.qa.vivat.pages.MainPage
at ru.sbtqa.tag.pagefactory.reflection.DefaultReflection.executeMethodByTitle(DefaultReflection.java:67)
at ru.sbtqa.tag.pagefactory.junit.CoreSteps.action_aroundBody4(CoreSteps.java:90)
at ru.sbtqa.tag.pagefactory.junit.CoreSteps$AjcClosure5.run(CoreSteps.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at ru.sbtqa.tag.pagefactory.allure.JunitReporter.handleStep(JunitReporter.java:25)
at ru.sbtqa.tag.pagefactory.aspects.JUnitCoreStepAspect.handleStep(JUnitCoreStepAspect.java:13)
at ru.sbtqa.tag.pagefactory.junit.CoreSteps.action(CoreSteps.java:89)
at ru.sbtqa.tag.stepdefs.ru.CoreStepDefs.action(CoreStepDefs.java:49)
at ✽.пользователь (нажимает кнопку) "Esc"(src/test/resources/features/123.feature:9)

**Comment by clicman** [comment]
Покажите как объявлен клаcc MainPage

**Comment by NasakB** [comment]
package ru.sbt.qa.vivat.pages;

import ru.sbtqa.tag.pagefactory.annotations.PageEntry;

@PageEntry(title = "Главная страница")
public class MainPage extends AnyPage {

    public MainPage() {
    }
}

**Comment by NasakB** [comment]
public abstract class AnyPage extends HTMLPage {
    private static final Configuration PROPERTIES = ConfigFactory.create(Configuration.class);
    private static final Logger LOG = LoggerFactory.getLogger(AnyPage.class);

    protected HtmlFindUtils findUtils = Environment.getFindUtils();

    @ElementTitle("Тер. Банк")
    @FindBy(id = "currentTerBnk")
    public Select slctTerBnk;

    @ElementTitle("Опер. день")
    @FindBy(id = "currentOperDays")
    public Select slctOperDays;

    @ElementTitle("Выход")
    @FindBy(xpath = "//tr[@class='head_main']//ancestor::tbody/tr[2]/td/a[contains(@href, 'logoutExitPage') " +
            "and text()='Выход']")
    public Button btnExit;

    @ElementTitle("Далее")
    @FindBy(xpath = "//td[@id='buttonNext']//input")
    public Button btnNext;

    @ElementTitle("Переход")
    @FindBy(xpath = "//td[@id='buttonNext']/div/input[1]")
    public Button btnContinue;

    @ElementTitle("ОК")
    @FindBy(id = "Далее")
    public Button btnOK;

    @ElementTitle("YES")
    @FindBy(id = "YES")
    public Button btnYES;

    @ElementTitle("Отмена")
    @FindBy(id = "Cancel")
    public Button btnCancel;

    @ElementTitle("Министерство")
    @FindBy(xpath = "//td[@id='fedOrgan']/select")
    public Select slctFedOrgan;

    @ElementTitle("Серия ПД")
    @FindBy(xpath = "//td[@id='idPersWork']/input[@name='penFilter.persWorkSeria']")
    public TextInput inputPDSeria;

    @ElementTitle("Номер ПД")
    @FindBy(xpath = "//td[@id='idPersWork']/input[@name='penFilter.persWorkNumber']")
    public TextInput inptPDNumber;

    @ElementTitle("Разрешение на выплату пенсии серия")
    @FindBy(xpath = "//input[@name='penFilter.PLstSer']")
    public TextInput inptPLstSer;

    @ElementTitle("Разрешение на выплату пенсии номер")
    @FindBy(xpath = "//input[@name='penFilter.PLstNumb']")
    public TextInput inptPLstNumb;

    @ElementTitle("Фамилия")
    @FindBy(xpath = "//td[@id='fio']/input")
    public TextInput inptFio;

    @ElementTitle("Серия ЕДП")
    @FindBy(xpath = "//input[@name='penFilter.PLstSer']")
    public TextInput inputPLstSer;

    @ElementTitle("Номер ЕДП")
    @FindBy(xpath = "//input[@name='penFilter.PLstNumb']")
    public TextInput inputPLstNumb;

    @ElementTitle("Статус документа")
    @FindBy(xpath = "//td[@id='pStatus']/select")
    public Select slctPStatus;

    @ElementTitle("Поиск")
    @FindBy(id = "Find")
    public Button btnFind;

    @ElementTitle("Таблица: Лист ПД")
    @FindBy(id = "pensionListOptions")
    public Table tblPensionList;

    @ElementTitle("Статус ПД")
    @FindBy(xpath = "//table[@id='pensionListOptions']//tbody//tr[2]//td[9]")
    public WebElement txtStatus;

    @ElementTitle("Esc")
    @FindBy(id = "Exit")
    public Button btnEsc;

    @ElementTitle("Ошибка")
    @FindBy(xpath = "//div[@style='text-align:center;background-color:#800000;color:#FFD0D0;padding:3px']")   //    @FindBy(xpath = "/html/body/div[2]")
    public TextBlock txtError;

    @ElementTitle("Назад")
    @FindBy(id = "Назад")
    public Button btnBackspace;

    public AnyPage(FieldDecorator decorator) {
        super(decorator);
    }

    public AnyPage() {
    }
    @ActionTitle("очищает поле")
    public void clearField(String elementTitle) {
        WebElement elem = findUtils.find(elementTitle);

        for(int i = elem.getText().length(); i >=0; i--){
            elem.sendKeys(Keys.BACK_SPACE);
        }
    }

    @ActionTitle("выходит из системы")
    public void outOfSystem() {
        btnExit.click();
        try {
//            Alert alert = getDriver().switchTo().alert();
//            Alert alert = Environment.getDriverService().getDriver().switchTo().alert();
            ru.sbtqa.tag.pagefactory.web.support.Alert alert = new ru.sbtqa.tag.pagefactory.web.support.Alert();
            alert.accept();
        }
        catch (NoAlertPresentException e){
            LOG.info("Отсутствует allert на странице!", e);
        }
    }
}

**Comment by NasakB** [comment]
Разобрался, дело было в описании шага
пользователь (нажимает кнопку) "Esc"
Необходимо было писать без скобок
пользователь нажимает кнопку "Esc"
