### ISSUE TITLE
[ERROR] io.qameta.allure.AllureLifecycle - Could not start step: no test case running

### ISSUE THREAD

**Issue by NasakB** [sbtqa/page-factory-2#226]
Прошу помочь разобрать с ошибкой [ERROR] io.qameta.allure.AllureLifecycle - Could not start step: no test case running

лог:
    * пользователь заполняет поле "Серия поручения" "86"                                                                                           # CoreStepDefs.fill(String,String)
[ERROR] io.qameta.allure.AllureLifecycle                   - Could not start step: no test case running
[ERROR] io.qameta.allure.AllureLifecycle                   - Could not stop step: no step running
    * пользователь заполняет поле "Номер поручения" "440710"                                                                                       # CoreStepDefs.fill(String,String)
[ERROR] io.qameta.allure.AllureLifecycle                   - Could not start step: no test case running
[ERROR] io.qameta.allure.AllureLifecycle                   - Could not stop step: no step running
    * пользователь заполняет поле "Фамилия" "МАСЛОВ"                                                                                               # CoreStepDefs.fill(String,String)
[ERROR] io.qameta.allure.AllureLifecycle                   - Could not start step: no test case running
[ERROR] io.qameta.allure.AllureLifecycle                   - Could not stop step: no step running
    * пользователь заполняет поле "Имя" "МАТВЕЙ"                                                                                                   # CoreStepDefs.fill(String,String)
[ERROR] io.qameta.allure.AllureLifecycle                   - Could not start step: no test case running
[ERROR] io.qameta.allure.AllureLifecycle                   - Could not stop step: no step running
    * пользователь заполняет поле "Отчество" "ВЯЧЕСЛАВОВИЧ"                                                                                        # CoreStepDefs.fill(String,String)
[INFO] ru.sbt.qa.vivat.utils.CommonFunctions              - Пользователь в выпадающем списке Категория выплатывыбирает значение 
[ERROR] io.qameta.allure.AllureLifecycle                   - Could not start step: no test case running
[ERROR] io.qameta.allure.AllureLifecycle                   - Could not stop step: no step running
[ERROR] io.qameta.allure.AllureLifecycle                   - Could not add attachment: no test is running

**Comment by NasakB** [comment]
pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>ru.sbtqa.pprb</groupId>
    <artifactId>xxxxxxx</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <allure.version>1.4.0</allure.version>
    
    <aspectj.version>1.9.3</aspectj.version>
    <hostname>${env.COMPUTERNAME}</hostname>
    <pf2.version>11.1.1</pf2.version>
    <maven.build.timestamp.format>yyyy/MM/dd/'${hostname}'-HH-mm</maven.build.timestamp.format>
    <allure.results.directory>${project.build.directory}/allure-results</allure.results.directory>
</properties>

<dependencies>
    <dependency>
        <groupId>ru.sbtqa.tag.pagefactory</groupId>
        <artifactId>html-plugin</artifactId>
        <version>${pf2.version}</version>
        <type>jar</type>
    </dependency>

    <dependency>
        <groupId>ru.sbt.qa</groupId>
        <artifactId>datagens</artifactId>
        <version>2.2</version>
    </dependency>

    <dependency>
        <groupId>com.sikulix</groupId>
        <artifactId>sikulixapi</artifactId>
        <version>1.1.2</version>
        <exclusions>
            <exclusion>
                <groupId>com.sikulix</groupId>
                <artifactId>sikulix2tigervnc</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

    <dependency>
        <groupId>ru.sbrf.vivat.qa</groupId>
        <artifactId>vivat-files</artifactId>
        <version>1.0.2</version>
    </dependency>

</dependencies>

<build>
    <pluginManagement>
        <plugins>
            
            <plugin>
                <groupId>ru.sbt.qa</groupId>
                <artifactId>sbtalm-maven-plugin</artifactId>
                <version>3.2.6</version>
                <configuration>
                    <almProperties>src/test/resources/config/alm.properties</almProperties>
                    <commentTemplate>src/test/resources/config/alm-comment.html</commentTemplate>
                    
                    <dataFolder>${allure.results.directory}</dataFolder>
                </configuration>
            </plugin>
            
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
                <version>2.5</version>
            </plugin>
        </plugins>
    </pluginManagement>

    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.21.0</version>
            <configuration>
                <junitArtifactName>junit:junit</junitArtifactName>
                <testFailureIgnore>false</testFailureIgnore>
                <skipTests>false</skipTests>
                <argLine>
                    -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    -Dcucumber.options="--plugin io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm --plugin pretty"
                    -Dfile.encoding=UTF-8
                </argLine>
            </configuration>
            <dependencies>
                <dependency>
                    <groupId>org.aspectj</groupId>
                    <artifactId>aspectjweaver</artifactId>
                    <version>${aspectj.version}</version>
                </dependency>
            </dependencies>
        </plugin>

        
        <plugin>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-maven</artifactId>
            <version>2.9</version>
        </plugin>
        
        
        <plugin>
            <artifactId>maven-resources-plugin</artifactId>
            <version>3.0.2</version>
            <executions>
                <execution>
                    <id>copy-resources</id>
                    <phase>validate</phase>
                    <goals>
                        <goal>copy-resources</goal>
                    </goals>
                    <configuration>
                       <outputDirectory>${allure.results.directory}</outputDirectory>
                        <resources>
                            <resource>
                                <directory>src/test/resources</directory>
                                <includes>
                                    <include>allure.properties</include>
                                    <include>categories.json</include>
                                </includes>
                            </resource>
                        </resources>
                    </configuration>
                </execution>
            </executions>
            <configuration>
                <encoding>${project.build.sourceEncoding}</encoding>
            </configuration>
        </plugin>
        
    </plugins>
</build>
</project>

**Comment by clicman** [comment]
@SandraBarmina это то, о чем я тебе говорил.

**Comment by NasakB** [comment]
Есть решение?

**Comment by clicman** [comment]
Это баг. Займемся в ближайшее время.

вт, 23 апр. 2019 г. в 12:51, NasakB <notifications@github.com>:

**Comment by kolik929** [comment]
Есть новости по прогрессу? когда можно ждать исправления?

**Comment by clicman** [comment]
А на 13,0,1 воспроизводится?

**Comment by kolik929** [comment]
На последнем allure 2.12.1 воспроизводится.

**Comment by clicman** [comment]
Нет, не про аллюр здесь, а про pf2. Надо проверить на последнем pf2 - он сецчас уже .13.0.2

**Comment by NasakB** [comment]
На 13.0.2 воспроизводится!

**Comment by clicman** [comment]
Ok. завтра попробую воспроизвести

**Comment by clicman** [comment]
Please check version 13.0.3

**Comment by clicman** [comment]
@NasakB @kolik929 please confirm the fix helps

**Comment by NasakB** [comment]
нет изменения! 13.0.3

**Comment by clicman** [comment]
Надо лично связаться и обсудить. Я там где нашёл, поправил.

**Comment by NasakB** [comment]
> Надо лично связаться и обсудить. Я там где нашёл, поправил.

**Comment by NasakB** [comment]
Ошибка решена.
В классе-страниц содержал пустой конструктор.
Необходимо было добавить вызов родительского конструктора, командой super()

**Comment by himanshusoni30** [comment]
[main] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
inputStream: java.io.FileInputStream@1e7f19b4
workbook: Name: /xl/workbook.xml - Content Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml
Sheet: Name: /xl/worksheets/sheet1.xml - Content Type: application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml
[main] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
[main] ERROR io.qameta.allure.AllureLifecycle - Could not update step: no step running
[main] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
[main] ERROR io.qameta.allure.AllureLifecycle - Could not update step: no step running
[main] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
[main] ERROR io.qameta.allure.AllureLifecycle - Could not start step: no test case running
[main] ERROR io.qameta.allure.AllureLifecycle - Could not update step: no step running
[main] ERROR io.qameta.allure.AllureLifecycle - Could not stop step: no step running
TestChooseOrganizationLink :: $$Finished$$
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 23.988 s <<< FAILURE! - in TestSuite


I am getting this Error. Could you please tell me how to fix this issue?
