### ISSUE TITLE
incorrect parsing props dataprovider

### ISSUE THREAD

**Issue by Sergo101010100** [sbtqa/page-factory-2#246]
pf2 12.0.3
properties-provider 5.0.0

Есть настройка
kafka.servers = <хост>:<порт>,<хост>:<порт>

При использовании DataFactory.getDataProvider().get("kafka.servers")  получаю значение в виде "["<хост>:<порт>", "<хост>:<порт>"]"

То есть в виде массива, а это одна строка

**Comment by clicman** [comment]
Fixed in 12.0.4
