### ISSUE TITLE
getElementByTitle 12.0.3 not find element

### ISSUE THREAD

**Issue by Sergo101010100** [sbtqa/page-factory-2#250]
Page с элементом

@PageEntry(title = "Редактирование дополнительных списков списка")
public class ListEditPage extends BackOfficeBasePage 

    @ElementTitle("Значение")
    @FindBy(xpath = "//input[@name='value']")
    private WebElement value;

Есть Action
`@ActionTitle("не доступно для редактирования")
public void onPageEditAble(String element) {
    WebElement webElement;
    try {
        webElement = getElementByTitle(element);
    } catch (ElementSearchError | Exception var4) {
        LOG.trace(FAILED_TO_FIND_ELEMENT_BY_TITLE, element, var4);
        webElement = waitUntilElementAppearsInDom(By.partialLinkText(element));
    }
    Assert.assertEquals("Поле " + element + " доступно для редактирования", "hidden", webElement.getAttribute("type"));
}
`
getElementByTitle(element) падает, что веб-элемента нет, хотя он есть

Если сделать поиск через webdriver - веб элемент находится
`ExpectedConditions.visibilityOf(getWebDriver().findElement(By.xpath("//input[@name='value']")))`
![11](https://user-images.githubusercontent.com/48100063/58246502-e9d61f80-7d5f-11e9-9026-403d15bd44dd.png)

**Comment by SandraBarmina** [comment]
Элемент скрыт и дефолтное ожидание его появления, как следствие, не отработало.
Решение: использовать метод для поиска элемента без ожидания: ((HtmlFindUtils) Environment.getFindUtils().find("element name",false);
