### ISSUE TITLE
Тесты с использованием rest-plugin возвращают статус broken вместо failed

### ISSUE THREAD

**Issue by fonbeauty** [sbtqa/page-factory-2#254]
Проваленные тесты написанные с помощью rest-plugin возвращают статус broken вместо failed. Надо сделать, чтобы при провале Assert-а возвращался статус failed.

Пример:
Класс:
@Endpoint(method = Rest.GET, path = "/messenger/v1/WrongPathGetUpdates", title = "WrongPathGetUpdates")
public class WrongPathGetUpdates extends EndpointEntry {

@Validation(title = "resultBodyError")
public void resultBodyError(DataTable dataTable) {
    Map<String, String> data = CastUtils.toMap(dataTable);
    getResponse().body( "httpCode", equalTo(Integer.valueOf(data.get("httpCode"))));
    getResponse().body( "httpMessage", equalTo(data.get("httpMessage")));
    getResponse().body( "moreInformation", equalTo(data.get("moreInformation")));
    } 

Результат работы validate метода resultBodyError при отсутствии поля httpCode со значением 404 в теле ответа получаем:
ru.sbtqa.tag.api.exception.RestPluginException: Failed to execute validation rule "resultBodyError" in "WrongPathGetUpdates" endpoint entry
        at ru.sbtqa.tag.api.utils.ReflectionUtils.invoke(ReflectionUtils.java:46) 
        at ru.sbtqa.tag.api.EndpointEntryReflection.validate(EndpointEntryReflection.java:144) 
        at ru.sbtqa.tag.api.EndpointEntry.validate(EndpointEntry.java:159) 
        at ru.sbtqa.tag.stepdefs.ru.ApiStepDefs.validate(ApiStepDefs.java:56) 
        at ✽.система возвращает ответ "resultBodyError" с параметрами(src/test/resources/features/api_common.feature:23)
Caused by: java.lang.AssertionError: 1 expectation failed. 
JSON path httpCode doesn't match. 
Expected: <404> 
  Actual: null 
... 

и статус теста Broken, а должен быть статус Failed.

**Comment by kosteman** [comment]
Добрый день.
Пытался повторить ошибку на тестах самого rest-plugin версии 12.0.4

```
@Endpoint(method = Rest.POST, path = "client/post", title = "post with json", template = "templates/Client.json")
public class PostEndpointEntry extends EndpointEntry {

    @Header(name = CONTENT_TYPE)
    private String header;

    @Body(name = "id")
    private int id = Default.ID;

    @Body(name = "name")
    private String name = "";

    @Body(name = "email")
    private String email;

    public PostEndpointEntry() {
        super();
        email = Default.EMAIL;
        header = JSON_UTF_8.toString();
    }

    @Validation(title = "result")
    public void validate() {
        Assert.assertEquals(0, 1);
    }
}
```
Отчет выглядит так
![image](https://user-images.githubusercontent.com/10125178/58445336-831d8100-8126-11e9-8dbd-5657685efd4c.png)

Как версия pf2 используется (нужно попробовать последнюю, 12.0.4)? Как версия аллюр используется?

**Comment by clicman** [comment]
Это было в старых версиях. В последних это исправлено.

**Comment by fonbeauty** [comment]
На версии 13.0.1 воспроизводится, Версия allure 2.9

**Comment by clicman** [comment]
Allure надо 2.10

Отправлено с iPhone

**Comment by fonbeauty** [comment]
Перепроверил, поправил коммент, не воспроизводится
