### ISSUE TITLE
Не верно проставляется cookie в rest плагине

### ISSUE THREAD

**Issue by justVitalius** [sbtqa/page-factory-2#261]
Метод addCookie() добавляет куки в мапу headers, а метод getCookies() берет мапу из cookies. https://github.com/sbtqa/page-factory-2/blob/b8325e5a2247a08a173bf7ff49d336368f6f651b/plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/storage/EndpointBlank.java#L64
В итоге куки невозможно прокинуть между rest-запросами

**Comment by clicman** [comment]
@kosteman ?

**Comment by kosteman** [comment]
https://github.com/sbtqa/page-factory-2/releases/tag/13.0.5
