### ISSUE TITLE
StringIndexOutOfBoundsException in DataReplacer.java при использовании DataJack

### ISSUE THREAD

**Issue by vmyasnik** [sbtqa/page-factory-2#264]
При использовании page-factroy-2 возникает StringIndexOutOfBoundsException 
в  
`replacedValue.delete(argument.getOffset(), argument.getOffset() + argument.getVal().length()).insert(argOffset, data);`

**Дано:**
**Данные:** 
_Vehicle.brand="BMW"
Vehicle.year="2014"
Vehicle.model="3 er"_

**Шаг:**
в feature файле:
`select car in classifier by brand "${Vehicle.brand}", year "${Vehicle.year}", model "${Vehicle.model}"`

Далее в дебаге на методе replaceStepArguments() класса ru.sbtqa.tag.pagefactory.data.DataReplacer
1 шаг: replacedValue= `select car in classifier by brand "BMW", year "${Vehicle.year}", model "${Vehicle.model}"` --замена верная
2 шаг: `select car in classifier by brand "BMW", year "2014${Vehicle.yeaehicle.model}"`
-- замена не верная

Зависимости:
page-factory-core=13.0.3  (пробовал меньшие версии, не помогло)
json-provider=5.0.2 

  Возможно связано с https://github.com/sbtqa/page-factory-2/pull/256

**Comment by clicman** [comment]
Не помгу воспроизвести.

**Comment by vmyasnik** [comment]
Забыл указать, из Идеи нормально раннится, валится при запуске из консоли 
`mvn -am -pl bdd_test test "-Dcucumber.options=--tags @tag`
Попробую сделать мини-проект, где воспроизводится.

**Comment by vmyasnik** [comment]
@clicman  Вот проект: https://github.com/vmyasnik/testDatajack
Воспроизводится и из идеи.

**Comment by clicman** [comment]
Там не хватает CucumberTest

**Comment by vmyasnik** [comment]
Добавил

**Comment by clicman** [comment]
дай мне плз права на коммит

**Comment by vmyasnik** [comment]
выслал инвайт

**Comment by clicman** [comment]
fixed in [13.0.4](https://github.com/sbtqa/page-factory-2/releases/tag/13.0.4)

**Comment by vmyasnik** [comment]
спасибо, все работает
