### ISSUE TITLE
Добавить возможность записи видео через аппиум

### ISSUE THREAD

**Issue by kosteman** [sbtqa/page-factory-2#273]
На уровне stepdefs + app.properties

**Comment by SvetlanaUtina** [comment]
по поводу записи тестов через настройку properties файл
video.enabled=true
video.path = путь к папке
почему записывает весь экран?

**Comment by kosteman** [comment]
Поскольку во фреймворке используется запись посредством monte-media. 
Запись видео с помощью appium в данный момент реализована и находится в стадии тестировании, в ближайшем минорном релизе она выйдет.
