### ISSUE TITLE
Производится излишнее преобразование

### ISSUE THREAD

**Issue by fonbeauty** [sbtqa/page-factory-2#281]
В библиотеке ru.sbtqa.tag.datajack.providers:json-provider производится излишнее преобразование передаваемых данных.

проверено на версиях 5.0.0, 5.0.1, 5.0.2 в составе page-factory 2 13.0.1 и 14.5.0 
При чтении данных из json файла производится излишнее преобразование.
Из примера: 4 в "4" и ["Hi!"] в [ \"Hi!\"], как получить такие же данные, как в json файле (без преобразований)?
То же самое происходит, если читать содержимое JSON файла из фичи.

Пример:
JsonDataProvider data = new JsonDataProvider(path, "SendTextBody");
String body = data.get("correctRequest").getValue();

файл SendTextBody.json
{
"correctRequest": {
"conversation_id": 4,
"text": "",
"render_type": "HTML",
"suggestions": ["Hi!"]
}
}

результат в body:
{
"conversation_id" : "4" ,
"text" : "" ,
"render_type" : "HTML" ,
"suggestions" : "[ \"Hi!\"]"
}

**Comment by clicman** [comment]
Правильно в этом случае делать
`testDataProvider.get("correctRequest").toString();`
