### ISSUE TITLE
help with props providers

### ISSUE THREAD

**Issue by Sergo101010100** [sbtqa/page-factory-2#290]
propetries provider 5.0.2

В application.properties настройка
`data.arraDelimiter=;`

И в одном из properties файле есть настройка
```
afd.db.save.hosts=server1;server2;server3
```

При попытке взять оттуда List<String> с помощью cпособа ниже получаю пустую строку
```
DataFactory.getDataProvider().get("afd.db.save.hosts").getStringValues()
```
В режиме дебага понял, что `DataFactory.getDataProvider().get("afd.db.save.hosts").getValues()` возвращает объект `BasicDBList` уже внутри которого коллекция.

Вопрос - как вытащить коллекцию?

**Comment by clicman** [comment]
Ошибка в параметре:
![image](https://user-images.githubusercontent.com/1079535/68102392-12646700-ff05-11e9-98a3-320529868d91.png)

**Comment by Sergo101010100** [comment]
Это я опечатался

**Comment by clicman** [comment]
Fixed in [datajack-5.1.0](https://github.com/sbtqa/datajack/releases/tag/5.1.0)

**Comment by clicman** [comment]
https://github.com/sbtqa/page-factory-2/releases/tag/14.9.0
