### ISSUE TITLE
There is no regular expression for method: "@Когда("^(?:пользователь |он )?очищает поле$")"

### ISSUE THREAD

**Issue by grebenkovia** [sbtqa/page-factory-2#302]
clearField method asks the user "String elementTitle", that's why 
Override must have a regular expression

Expectation:
 @Когда("^(?:пользователь |он )?очищает поле "([^"]*)" $")
 public void clearField(String elementTitle) throws PageException {
Now: 
    @Когда("^(?:пользователь |он )?очищает поле$")
public void clearField(String elementTitle) throws PageException {

**Comment by clicman** [comment]
Fixed in verison [15.3.1](https://github.com/sbtqa/page-factory-2/releases/tag/15.3.1).
