### ISSUE TITLE
gherkin.ParserException$CompositeParserException

### ISSUE THREAD

**Issue by yaroslav796** [sbtqa/page-factory-2#307]
Добрый вечер!
Ошибка при запуске тестов...
cucumber.runtime.CucumberException: Failed to parse resource at: file:src/test/resources/features/test.feature
Caused by: gherkin.ParserException$CompositeParserException: 
Parser errors:
(3:1): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '����������: ����������'
(6:3): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '��������: ��������'
(7:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got '*  ������������ ��������� �� �������� "������� ��������"'
(9:0): unexpected end of file, expected: #TagLine, #FeatureLine, #Comment, #Empty
--------------------------------------------------------------------------------------------------------
как выглядит feature файл
`
#language:ru
@Test1
Функционал: Функционал

    Сценарий: Сценарий

      * пользователь находится на странице "Главная страница"`
Никакая кодировка в UTF-8 и UTF-8 без BOM не помогает.
----------------------------------------------------------------------------------------------------------
POM файл
` <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <aspectj.version>1.8.10</aspectj.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>ru.sbtqa.tag.pagefactory</groupId>
            <artifactId>web-plugin</artifactId>
            <version>15.4.3</version>
        </dependency>
        <dependency>
            <groupId>ru.sbtqa.tag.pagefactory</groupId>
            <artifactId>rest-plugin</artifactId>
            <version>15.4.3</version>
        </dependency>
        <dependency>
            <groupId>ru.sbtqa.tag.pagefactory</groupId>
            <artifactId>html-plugin</artifactId>
            <version>15.4.3</version>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-cucumber2-jvm</artifactId>
            <version>2.13.3</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.20</version>
            <configuration>
                <argLine>
                    -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    -Dcucumber.options="--plugin io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm --plugin pretty"
                </argLine>
            </configuration>
            <dependencies>
                <dependency>
                    <groupId>org.aspectj</groupId>
                    <artifactId>aspectjweaver</artifactId>
                    <version>${aspectj.version}</version>
                </dependency>
            </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
`

![image](https://user-images.githubusercontent.com/48731637/81656151-754c3300-943f-11ea-828f-18fdb210f94f.png)

**Comment by clicman** [comment]
Рантайм Windows?

**Comment by yaroslav796** [comment]
Решение проблемы
![Screenshot_16](https://user-images.githubusercontent.com/48731637/82292263-40962980-99b3-11ea-948b-31d469326e46.png)

**Comment by clicman** [comment]
Да, так и есть. Поэтому уточнял про рантам.
