### ISSUE TITLE
Не возможно использовать селекторы, как UIAutomator и accesabilytyid c аннотацией @AndroidFindBy

### ISSUE THREAD

**Issue by sichevmi** [sbtqa/page-factory-2#317]
Приветствую. Решили попробовать возможности Mobile plugin. Столкнулись с проблемой в текущем шаблоне проектирования. Как видится  page-factory-2 умеет пользовать две стратегии поиска name и id. Мы пытались прописать в качестве стратегии поиска UIAutomator и accesabilytyid, при любых реализациях тест выдает ошибку. Ниже два варианта, которые пробовали на Page и описание ошибки:
@AndroidFindBy (uiAutomator = "new UiSelector().descriptionContains(\"Open navigation drawer\")"
@AndroidFindBy (accesabilyty = "Open navigation drawer)"
org.openqa.selenium.InvalidSelectorException: Locator Strategy 'name' is not supported for this session
Возможно идем не в ту сторону. В документации про плагин не нашли сведений.

**Comment by kosteman** [comment]
Добрый день.
Необходимо глянуть на сам элемент, который пытаетесь идентифицировать. Как он определяется инспектором в [аппиум десктоп](https://github.com/appium/appium-desktop)?
В случае если это кнопка с текстом "Open navigation drawer", то возможно вам стоит попытаться определить ее как 
`@AndroidFindBy (uiAutomator = "new UiSelector().text("Open navigation drawer")"`
Во второй же строке у вас как несколько ошибок, но думаю это просто опечатки, так как ide вам не дала бы скомпилировать так код. Должно быть так
`@AndroidFindBy (accessibility = "Open navigation drawer")`
В любом случае, я проверил, такая идентификация работает в актуальной версии фреймворка (Сейчас ведется дополнительная работа по поддержке андроид тестов, но она не связана с идентификацией элементов: будет исправлена запись видео для андроид тестов, тап по элементу на андроиде и другие проблемы)

Из собственного опыта могу отметить, что в случае с реактом и поддержкой ios и android, чтобы не возникало проблем с идентификацией, элемент должен быть сверстан следующим образом
<img width="508" alt="Screenshot 2020-07-14 at 09 30 04" src="https://user-images.githubusercontent.com/10125178/87399579-c2848680-c5e1-11ea-99aa-22a79a258a29.png">
test-id и accessible - для ios
accessibiltyLabel - для андроид
В таком случае элемент будет определяться в инспекторе 
на ios
![Screenshot 2020-07-14 at 15 08 38](https://user-images.githubusercontent.com/10125178/87401179-011b4080-c5e4-11ea-939b-818b9230691a.png)
на android
![Screenshot 2020-07-14 at 15 02 12](https://user-images.githubusercontent.com/10125178/87401203-08424e80-c5e4-11ea-96d4-9ce00d363693.png)
и может быть описан как
```
    @iOSXCUITFindBy(accessibility = "button")
    @AndroidFindBy(accessibility = "button")
    private MobileElement button;
```
такой тест будет работоспособен в обеих осях
