### ISSUE TITLE
Documentation page misses the content

### ISSUE THREAD

**Issue by VarvaraKorolApica** [sbtqa/page-factory-2#322]
Hi Guys, 

Please, check out the documentation page screenshot.
This is what it's available if I go to https://docs.sbtqa.ru/
<img width="1315" alt="Screenshot 2020-10-20 at 10 36 15" src="https://user-images.githubusercontent.com/26868346/96561694-30ff7180-12c0-11eb-91dc-ba506008269d.png">

Btw, it would be so great to have it in English too.

**Comment by clicman** [comment]
Hi! This idea had a long live in my head. But it’s no time to perform it :( 
So, if you can contribute an English version , welcome to the team!

**Comment by clicman** [comment]
Damn! Just seen what it broken. Thanks 🙏 
Will fix it soon.

**Comment by VarvaraKorolApica** [comment]
Thanks!

**Comment by VarvaraKorolApica** [comment]
> Hi! This idea had a long live in my head. But it’s no time to perform it :(
> So, if you can contribute an English version , welcome to the team!

Thanks for inviting me. :) I'll see, if I get time to do that, though.

**Comment by clicman** [comment]
It seems doc become too popular and GitHub denied access to its API:
`{"message":"API rate limit exceeded for 104.196.57.92. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
`

**Comment by clicman** [comment]
Worse. it was denied travis:
![Uploading image.png…]()

**Comment by clicman** [comment]
Temorarly fixed:
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/1079535/96581889-b73da700-1304-11eb-8e06-c7b38b13688e.png">

Do not close an issue. Will fix it permanently soon.

**Comment by VarvaraKorolApica** [comment]
Thanks!

**Comment by clicman** [comment]
Fixed in [7388414](https://github.com/sbtqa/page-factory-2/commit/7388414a797b698e058ae6679f95445c547884fb)
