### ISSUE TITLE
Через параметр scenario outline невозможно достать поле из datajack или фрагмент

### ISSUE THREAD

**Issue by Tokksa** [sbtqa/page-factory-2#324]
Тестовый проект: https://github.com/Tokksa/test-pf2
Проблемы: 
- датаджек в структуре сценария, как параметр.
- фрагмент в структуре сценария, как параметр.
- все вместе.

**Comment by clicman** [comment]
Да, фрагмент вытащить из DataJack не получится в случае, если это значение находится в примере структуры сценария, так как при подстановке фрагмента будет генерироваться 4 совершенно разных сценария, что нарушит как раз структуру сценария.

Подстановка из примера просто параметр шага работает ок.
Подстановка фрагмента напрямую из DataJack работает ок.
