### ISSUE TITLE
Параметризованный фрагмент

### ISSUE THREAD

**Issue by MurtazinArtur** [sbtqa/page-factory-2#326]
Доброго времени суток.
Можно ли как то настроить задание параметров для выполнения фрагмента в столбик?
Когда 2-3 параметра используются, то их расположение в строчку ещё ничего, но когда этих параметров становится хотя бы больше 5 очень неудобно прописывать в строку.
Отсюда вопрос можно ли как то с помощью конфига или переопределения изменить порядок чтения параметров?

**Comment by clicman** [comment]
Как вариант, прописывать только ключ от json или excel в параметрах. А далее уже по этому ключу в степдефе забирать данные датаджеком из файла сттесьовыми данными. Так будет на много лаконичнее и удобнее

**Comment by MurtazinArtur** [comment]
А можно какой-нибудь "например"?

**Comment by clicman** [comment]
[Здесь](https://github.com/sbtqa/page-factory-2/blob/master/plugins/web-plugin/src/test/resources/features/dataBinding.feature) можно посмотреть, как ссылаться на данные из фич.

А потом, где-то в коде так:
```
    public void getParams(String userName) throws DataException {
        TestDataProvider user = DataFactory.getDataProvider().get(userName);
        String firstName = user.get("first_name").getValue();
        String lastName = user.get("last_name").getValue();;
        String passport = user.get("passport_number").getValue();;
    }
```

**Comment by MurtazinArtur** [comment]
Спасибо огромное, очень помогло
