### ISSUE TITLE
Ошибка при отправке Rest запроса

### ISSUE THREAD

**Issue by MurtazinArtur** [sbtqa/page-factory-2#336]
Добрый день написал тест по отправке запроса, как указано в документации и при этом тест падает с ошибкой. Буду очень признателен если поможете разобраться в чём причина. Заранее прошу прощения, хотел все данные в файлах разместить, но у меня не получается добавить сюда файлы 
Версия page factory 13,0,3

**Comment by kosteman** [comment]
Добрый день.
Попробуйте сменить тип переменной id с int на String.

**Comment by MurtazinArtur** [comment]
Добрый день.
С полем id типа String всё работает без проблем.
НО. Я хотел бы передавать int и в документации указано что такая возможность есть.
Либо не корректно работает сам фреймворк, либо некорректна документация.
