### ISSUE TITLE
Возможность создавать REST запросы в которых есть JsonArray

### ISSUE THREAD

**Issue by MurtazinArtur** [sbtqa/page-factory-2#343]
Добрый день.
Есть необходимость создать REST запрос с Body следующей структуры:
{ 
"channel": "test-channel',
"requestId": "1",
"requisites": [
     {
      "path": "home",
      "values": [
          "12356"
          "98751"
                     ]
      }
   ]
}
Как это сделать стандартными методами представленными в проекте я не нашёл.
Попытка сделать кастомный класс так же не привела к успеху. Как мне кажется, всё сводится к тому что метод
send у EndpointEntry воспринимает исключительно String и любая попытка задать полям Endpointa тип отличный от String приводит к ошибкам при запуске тестов.

Буду признателен за оказание любой помощи

**Comment by clicman** [comment]
Fixed in 16.0.0
