### ISSUE TITLE
Переопределение DataProvider

### ISSUE THREAD

**Issue by nstreltsov** [sbtqa/page-factory-2#356]
Привет.
Можно ли зарегистровать свой TestDataProvider? В коде не нашел, такое ощущение что можно использовать только те, которые находятся в пакете "ru.sbtqa.tag.datajack.providers.*". Есть GeneratorCallback, но не смог разобраться что это такое и как с этим работать.
Для чего мне надо переопределить стандартные реализации TestDataProvider:
У меня мультимодульный maven-проект, есть отдельный модуль с общими тестовыми данными и для каждого проекта, который тестируем создан отдельный модуль, при этом для каждого проекта есть еще и свои тестовые данные. Например, текущая реализация метода JsonDataProvider#fromCollection подразумевает что данные храняться в папке, которую я указал в properties и не позволяет загружать данные из разных мест, например, взять данные из модуля с тестовыми данными и их самого запускаемого проекта. Тестовых данных достаточно много и поддерживать актуальность одних и тех же тестовых данных в разных модулях довольно накладно. 
В дальнейшем планируется создание дата генератора, который будет как хранить, так и генерировать тестовые данные, и представлять из себя отдельное приложение. В этом случае вообще не будет файлов в самом проекте с тестами, а надо будет дергать rest api отдельного сервиса.

**Comment by clicman** [comment]
Привет! На текущий момент дата провайдеры вшиты в core ([смотреть сюда](https://github.com/sbtqa/page-factory-2/blob/e7454b55afec1570f8148e617ac00b6bd269985f/page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/data/DataFactory.java#L27). Но в принципе, там все достаточно законтрактовано, чтобы от этого отвязаться. Посмотри на [интерфейс](https://github.com/sbtqa/datajack/blob/master/datajack-api/src/main/java/ru/sbtqa/tag/datajack/TestDataProvider.java), если пот него сможешь подстроиться, делая свой провайдер, то можно подумать над тем, чтобы отвязаться от этого предопределения и вынести это в конфиг.

**Comment by nstreltsov** [comment]
Привет.
Вариант с реализацией интерфейса и выноса в конфиг мне кажется очень даже ничего. В таком случае будет более гибко и любой желающий сможет сделать DataProvider под любой тип хранения данных.

**Comment by clicman** [comment]
@nstreltsov глянь сюда https://github.com/sbtqa/page-factory-2/pull/357
Так ок? Это то, что можно сделать без особого рефакторинга. Здесь естественно ты можешь, к примеру в data.db - написать connection string, либо вообще что угодно, а потом как тебе надо распарсить в своем конструкторе.

**Comment by nstreltsov** [comment]
Да, выглядит как то, что надо. Спасибо за оперативное решение.

**Comment by clicman** [comment]
https://github.com/sbtqa/page-factory-2/releases/tag/16.2.0 доступно в этом релизе.
