### ISSUE TITLE
Поддержка нескольких URL при тестировании API

### ISSUE THREAD

**Issue by nstreltsov** [sbtqa/page-factory-2#358]
Привет. 
Сейчас можно добавить только один "api.baseURI", но часто приходится тестировать интеграцию. В классе EndpointEntry в методе send() есть четкая привязка к "PROPERTIES.getBaseURI()", поэтому нельзя использовать более одного url в проекте. Добавьте, пожалуйста, возможность переопределять url в ходе выполнения теста.

**Comment by clicman** [comment]
Привет! Опиши, как ты это видишь, глобальное переопределение или для текущего контекста?

**Comment by nstreltsov** [comment]
Наверное самый простой вариант: в этом классе сделать public void setBaseUri(String uri), далее при наследовании от этого класса переопределять этот метод и устанавливать url для текущего контекста. Либо сделать на уровне аннотации @Endpoint добавил туда поле url , куда подставлять значение из environment.properties

**Comment by clicman** [comment]
просто тут для мультитреда надо подумать. чтобы не путалось

**Comment by nstreltsov** [comment]
я честно говоря глубоко не копал как там все работает, но прям очень очень надо чтобы эта задача была решена :(

**Comment by kosteman** [comment]
@nstreltsov 
Привет.
Так пойдет https://github.com/sbtqa/page-factory-2/pull/359 ?

**Comment by nstreltsov** [comment]
Привет.
Если я правильно понимаю код, то так не очень подходит. 
У нас перед запуском автотестов сам тестируемый продукт поднимается в докерах и каждый раз host тестируемых продуктов будет разный, потому что  в нем есть номер версии. Можно ли сделать чтобы host() в аннотации Endpoint брался из переменных, которые мы передаем при запуске тестов?
например:
 @Endpoint(method = Rest.GET, host="${api.baseUri.product1}", path = "/login", title = "Авторизация в продукте 1")
public class LoginEntryApp1 extends EndpointEntry{}

 @Endpoint(method = Rest.GET, host="${api.baseUri.product2}", path = "/login", title = "Авторизация в продукте 2")
public class LoginEntryApp2 extends EndpointEntry{}

а запуск тестов mvn test -Dapi.baseUri.product1="https://host1" -Dapi.baseUri.product1="https://host1"

**Comment by kosteman** [comment]
https://github.com/sbtqa/page-factory-2/pull/359/commits/b653a3856305a79042c086b21954c4ac09c66e10

В качестве временного решения, если нужно в рантайме менять хост-порт по которому будет обращаться EndpointEntry, могу предложить следующий вариант.

Чтобы изменить host параметр для EndpointEntry необходимо переопределить метод send
```
    @Override
    public void send() {
        this.setHost("http://localhost:8888");
        super.send();
    }
```

**Comment by kosteman** [comment]
https://github.com/sbtqa/page-factory-2/pull/359/commits/d88da0aeab7af64f17d10593cf01fca77b0385a3

Добавил возможность указывать хост как плейсхолдера вида `host="${env.myHost}"`. В мавен нужно будет передать это параметр как `mvn clean test -Denv.myHost=https://localhost:8888`

**Comment by nstreltsov** [comment]
Спасибо большое, опубликуйте плиз)

**Comment by clicman** [comment]
https://github.com/sbtqa/page-factory-2/releases/tag/16.4.0
