### ISSUE TITLE
REST. Формирование body с пустыми структурами

### ISSUE THREAD

**Issue by oversquall** [sbtqa/page-factory-2#364]
Доброго дня. Столкнулся со следующей проблемой: сервер бракует входящие запросы (не проходит валидация по xsd), в которых есть пустые структуры вида "name": {   } В xsd указано, что либо её нет совсем, либо если есть, то должны быть обязательные поля в ней.

При формировании body, если я не передаю ни одного поля структуры, само тело структуры остаётся (в соответствии с шаблоном), хотя для тестируемого взаимодействия (в данном тест-сценарии) мне этот блок не нужен. И это приводит к ошибкам валидации. 

На примере. Есть шаблон для запроса:

> {
> 	"filter": {
> 		"accountInn": "${account Inn}",
> 		"controlDateFrom": "${controlDateFrom}"
> 	},
> 	"messageRq": {
> 		"employeeNumber": "${employeeNumber}",
> 		"task": {
> 			"statusCode": "${task-statusCode}",
> 			"types": "${types}"
> 		}
> 	},
> 	"paging": {
> 		"itemsPerPage": "${itemsPerPage}",
> 		"pageNum": "${pageNum}",
> 		"total": "${total}"
> 	}
> }

Передаю поля employeeNumber, task-statusCode, itemsPerPage. Получаю тело запроса:

> {
> 	"filter": {
> 	},
> 	"messageRq": {
> 		"employeeNumber": "00111987",
> 		"task": {
> 			"statusCode": "MOP Calling"
> 		}
> 	},
> 	"paging": {
> 		"itemsPerPage": "10"
> 	}
> }

Структура "filter" присутствует, но пуста. На сервере это приведет к ошибке валидации.

Покопавшись в коде, я не нашел возможности повлиять на сформированный body перед его отправкой. 
Подскажите, пожалуйста, есть ли возможность "схлопывать" пустые блоки до отправки запроса. А если нет, то можно ли реализовать эту возможность для нас.

**Comment by clicman** [comment]
https://github.com/sbtqa/page-factory-2/releases/tag/16.4.0

**Comment by oversquall** [comment]
Спасибо

**Comment by oversquall** [comment]
Выложите в sbtnexus.delta, пжл

**Comment by clicman** [comment]
Мы не работаем в сбере :)

**Comment by oversquall** [comment]
Жаль)
Не корректно отрабатывает удаление структур, остаются запятые от вышестоящих несхлопнутых плейсхолдеров.
На примере из вашего теста:
**исходный json**
> {
>   "minusOne": {
> 
>   },
>   "zero": { },
>   "first": "${first}",
>   "second": { },
>   "third": {
> 
> 
> 
>   },
>   "four":                 {}
> ,               "fifth":{},"sixth":{},"seventh":
> {            }
> } 

**преобразованный json**
> {
>    "first": "parameter",
>    }

**лог теста**
> 2021-12-01 17:24:45 DEBUG EndpointEntry: 70 -
> * system returns "works correctly"
> * system returns "works correctly"
> * getInstance getInstance
> * user sends request for "empty objects" with parameters 
> * user sends request for "empty objects" with parameters "(first-parameter}"
> 2021-12-01 17:24:45 DEBUG EndpointEntry: 70 - Request method:  POST
> Request URI: http://localhost:9998/client/typed-arrays
> Proxy: <none>
> Request params: <none>
> Query params: <none>
> Form params: <none>
> Path params: <none>
> Headers: 	Accept-*/*
> 				Content-Type-text/plain; charset-ISO-8859-1
> Cookies: <none>
> Multiparts: <none>
> Body:
> {
>    **"first": "parameter",**
>    }

**Comment by clicman** [comment]
@kosteman бага.

**Comment by oversquall** [comment]
Так же на работает для таких кейсов:
```
{
   "employeeNumber": "${employeeNumber}",
   "task": [
      {
         "statusCode": "${task.statusCode}",
         "types": "${types}"
      }
   ]
}
```
При передаче только **employeeNumber** преобразуется в:
```
{
   "employeeNumber": "${employeeNumber}",
   "task": [
      {

      }
   ]
}
```

**Comment by clicman** [comment]
https://github.com/sbtqa/page-factory-2/releases/tag/16.4.1
