### ISSUE TITLE
Отправка файлов multipart/form-data

### ISSUE THREAD

**Issue by nstreltsov** [sbtqa/page-factory-2#369]
Привет.
Можно ли отправить картинку на сервер с content-type=multipart/form-data? Если да, то как должны выглядеть поля Endpoint, в которых передаем картинку?
В RestAssured это выглядело бы примерно так:
given()
        .headers(httpHeaders)
        .contentType(MediaType.MULTIPART_FORM_DATA.toString())
        .multiPart("content", file1)
        .multiPart("content", file2)

Сам запрос формируется в методе EndpointEntry#buildRequest() добавьте плиз туда возможность указать multiPart с двумя параметрами наименование поля и файл

**Comment by kosteman** [comment]
Пригодился бы пример отправленного запроса

**Comment by nstreltsov** [comment]
@kosteman Пример запроса:
https://disk.yandex.ru/i/DeNEX6E7vYnCVg
https://disk.yandex.ru/i/U_DjPerVGSfVIg
    
Как решили проблему сейчас:
 ```
   @Override
    public void send() {
        String host = this.getClass().getAnnotation(Endpoint.class).host();
        RequestSpecification request = given()
                .contentType(ContentType.MULTIPART)
                .multiPart("banner[content]",new File( "src" + File.separator + "test" + File.separator + "resources" + File.separator + "data" + File.separator + "images" + File.separator + getImage()))
                .cookies("session", getSession());
        Response response = request.post(PlaceholderUtils.replaceTemplatePlaceholders(host)+ "/banners.json");
        ApiEnvironment.getRepository().add(this.getClass(), new ApiPair(request, response.then().log().all(true)));
        validate();
    }
```
