### ISSUE TITLE
Добавить в проверку в методе checkForm наименование поля

### ISSUE THREAD

**Issue by nstreltsov** [sbtqa/page-factory-2#370]
Сейчас при использовании шага `@Когда("^проверяет форму$")` когда в каком - то поле происходит несовпадение ожидаемых и актуальных значений много времени уходит на то, чтобы понять в каком именно поле ошибка.
Добавьте плиз вывод названия поля, в котором ошибка
    public T checkForm(DataTable dataTable) {
        Map<String, String> dataMap = dataTable.asMap(String.class, String.class);
        dataMap.forEach((key, value) ->
                Assert.assertEquals("Element **["+key+"]** value is not as expected.", getText(key), value)
        );
        return (T) this;
    }

**Comment by clicman** [comment]
Привет! Вот ты почти до PR дотянул. Как насчет делать пулл-реквест?

**Comment by nstreltsov** [comment]
ок, сделаю
