### ISSUE TITLE
В центральном репозитории нет последних версий

### ISSUE THREAD

**Issue by nstreltsov** [sbtqa/page-factory-2#373]
Привет.
А почему в центральном репозитории maven нет последних версий 16.4.2 и 16.4.3 ? Они там с какой-то задержкой публикуются?

**Comment by clicman** [comment]
Хммм.. что-то видать у них сломалось. такое бывает редко. @kosteman посмотри плз, и ели надо пропихни.

**Comment by clicman** [comment]
Хмммм... кажется они хотят денег. 
<img width="822" alt="image" src="https://user-images.githubusercontent.com/1079535/145787101-d7c9d002-bc6f-4ec3-a212-9eda5b0c5590.png">

**Comment by clicman** [comment]
Судя по всему сегодня должно все заработать:
<img width="763" alt="image" src="https://user-images.githubusercontent.com/1079535/145787712-484c8f53-a72d-402c-a751-38b2748a89bb.png">

**Comment by nstreltsov** [comment]
спасибо

**Comment by nstreltsov** [comment]
@clicman а не надо их заново публиковать?

**Comment by clicman** [comment]
что-что. договариваюсь с travis-ci чтобы дали нам опенсорц кредиов. Заявку отправил - ждем-с.

**Comment by nstreltsov** [comment]
да уж, зачем такие зависимости делать :(
проект то простенький, Jenkins за 10 минут настраивается

**Comment by clicman** [comment]
Ну дженкинс тоже где-то надо хостить. Мы же нон-профит, чисто по-приколу занимаемся и вкладывать туда свои средства не планируем. А донатить тоже желающих нет )

**Comment by nstreltsov** [comment]
а вы уже не сберовские?

**Comment by clicman** [comment]
Уже года три как )

**Comment by nstreltsov** [comment]
о как, ну тогда не скромный вопрос разрешил ли сбер выкладывать фреймворк в опенсорс?

**Comment by clicman** [comment]
Мы его делали дома в свободное время. Я конечно пытался его соберу отдать, но что-то не нашлось желающих

**Comment by clicman** [comment]
Ура!
<img width="972" alt="image" src="https://user-images.githubusercontent.com/1079535/145999190-cf242690-d481-49a4-b9fd-b19c4f540818.png">

**Comment by clicman** [comment]
https://github.com/sbtqa/page-factory-2/releases/tag/16.4.4
Поехало в централ, скоро будет там.

**Comment by nstreltsov** [comment]
Понятно, спасибо большое

**Comment by clicman** [comment]
Теперь сонатайп сломался. Ждем пока починят, плачем [сюда](https://issues.sonatype.org/browse/OSSRH-76064)

**Comment by nstreltsov** [comment]
@clickman что-то так и не вижу в репе новый релиз

**Comment by clicman** [comment]
я вот только что руками его пропихнул - надеюсь скоро появится. А вообще там у них проблема(ссылка выше) так и не решена.

**Comment by nstreltsov** [comment]
@clicman что-то вы делаете не так :)

**Comment by clicman** [comment]
Тупо ждём. Нексус не даёт деплоить. Все по тайм-аутам отваливается. 

Отправлено с iPhone

**Comment by clicman** [comment]
Ура!
<img width="526" alt="image" src="https://user-images.githubusercontent.com/1079535/146645535-2d13cc5d-e785-4603-895e-9dd6fa605c43.png">

**Comment by clicman** [comment]
В централе - закрываю
