### ISSUE TITLE
rest: Проблема десериализации объектов с большими числами

### ISSUE THREAD

**Issue by oversquall** [sbtqa/page-factory-2#374]
Добрый день.
В ходе правок в рамках #367 был переработан обработчик json-структур для их корректного схлопывания (если они пустые).

Была задействована библиотека com.google.gson, однако, это привело к некорректному наполнению json, если в нем есть большие числа.
На этапе преобразования текстового json в объект

`Map<String, Object> data = new Gson().fromJson(jsonString, objectType);`

все числовые поля будут приведены к типу Double. Для маленьких чисел это не является проблемой (при обратной трансформации они заменят свои плейсхолдеры в ожидаемом виде), но на больших числах, например 18-значный Long: 123456789012345678 ляжет в объект в виде Double: 1.2345678901234568E17. При обратной трансформации, он в этом же виде перекочует в текстовый json.

Это проблема самой библиотеки Gson. Она была решена начиная с версии 2.8.8. Подробнее тут: [https://github.com/google/gson/pull/1290](url)

Возможный вариант фикса. Подключить новую библиотеку и заменить:

```
        if (isJsonArray) {
            ArrayList<?> array = new Gson().fromJson(jsonString, arrayType);
            return new GsonBuilder().setPrettyPrinting().create().toJson(jsonArrayCleaner(array));
        } else {
            Map<String, Object> data = new Gson().fromJson(jsonString, objectType);
            return new GsonBuilder().setPrettyPrinting().create().toJson(jsonObjectCleaner(data));
        }
```
на:
```
        Gson gson = new GsonBuilder()
                .setObjectToNumberStrategy(ToNumberPolicy.BIG_DECIMAL)
                .setPrettyPrinting()
                .create();

        if (isJsonArray) {
            ArrayList<?> array = gson.fromJson(jsonString, arrayType);
            return gson.toJson(jsonArrayCleaner(array));
        } else {
            Map<String, Object> data = gson.fromJson(jsonString, objectType);
            return gson.toJson(jsonObjectCleaner(data));
       }
```

**Comment by oversquall** [comment]
Привет. подготовил, но:
14:17:42.912: [page-factory-2] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/fix-rest-deserializing_objects_with_large_numbers:fix-rest-deserializing_objects_with_large_numbers --set-upstream
remote: Permission to sbtqa/page-factory-2.git denied to oversquall.
fatal: unable to access 'https://github.com/sbtqa/page-factory-2.git/': The requested URL returned error: 403

**Comment by clicman** [comment]
Ты форкни, у себя сделай в репозитории, а потом пр сделай в этот

**Comment by oversquall** [comment]
ok
