### ISSUE TITLE
Уязвимость в jquery 3.3.1

### ISSUE THREAD

**Issue by hooligan4ik95** [sbtqa/page-factory-2#380]
Здравствуйте! При проверке на уязвимости web-plugin выяснилось, что в page-factory-core есть уязвимость в виде версии 3.3.1 jquery (если я правильно понял, первой версией без уязвимостей считается 3.5.0).
Подскажите, есть ли возможность попробовать перейти на jquery 3.5.0?

**Comment by clicman** [comment]
Я не вижу там в зависимостях core jquery

**Comment by clicman** [comment]
Оно там только в тестовом webapp лежит, как статический скрипт. Но оно используется только для самотестов фреймворка и никак не влияет
