### ISSUE TITLE
Повышение версии selenium 4.4.0

### ISSUE THREAD

**Issue by JonstsnVilmus** [sbtqa/page-factory-2#382]
Какие сроки на повышении версии selenium <version>4.4.0</version>?

**Comment by kosteman** [comment]
https://github.com/sbtqa/page-factory-2/releases/tag/17.0.1
В этой версии уже 4.5.0

**Comment by JonstsnVilmus** [comment]
не вижу что бы использовалось [Selenium DevTools V104

**Comment by kosteman** [comment]
Фреймворк явно эту зависимость не тянет. Можете добавить ее вручную.

**Comment by JonstsnVilmus** [comment]
при добавлении зависимостей сталкиваюсь с конфликтами maven Selenium DevTools V104 и Selenium DevTools V102
java.lang.NoSuchMethodError: 'io.netty.bootstrap.AbstractBootstrap io.netty.bootstrap.Bootstrap.channelFactory(io.netty.channel.ChannelFactory)'
