### ISSUE TITLE
rest-plugin - проблемы с кодировкой в API логах 

### ISSUE THREAD

**Issue by dmitrii-slayer** [sbtqa/page-factory-2#385]
Добрый день. Мигрировал проект с api-factory на rest-plugin и наткнулся на проблему с кодировкой в API логах в Allure отчёте.
- скриншот Allure вложения - https://github.com/dmitrii-slayer/page-factory-2-example/blob/dmitrii-slayer-patch-1/src/test/resources/encoding-issue-allure-attach.png 
Такие же иероглифы потом отображаются в самом Allure отчёте
- Воспроизводится в тестах самого rest-plugin - например fillOnTheFlyTest из JUnitTests - достаточно просто добавить какой-то текст с кириллицей в тестовые данные.
Вместо "default_person- какой-то текст123@google.com" получаю default_person- ￐ﾺ￐ﾰ￐ﾺ￐ﾾ￐ﾹ-￑ﾂ￐ﾾ ￑ﾂ￐ﾵ￐ﾺ￑ﾁ￑ﾂ123@google.com" - https://github.com/dmitrii-slayer/page-factory-2-example/blob/dmitrii-slayer-patch-1/src/test/resources/encoding-issue-test.png
Понаставил принты в getPrintStream() в ToLoggerPrintStream и похоже что проблема не в аллюре, кодировка ломается где-то раньше - https://github.com/dmitrii-slayer/page-factory-2-example/blob/dmitrii-slayer-patch-1/src/test/resources/encoding-issue-ToLoggerPrintStream.png

**Comment by clicman** [comment]
Windows encoding problem. So try this:

<img width="707" alt="image" src="https://user-images.githubusercontent.com/1079535/212565106-3f8f4ea5-c825-415b-a82f-3d0090dfc342.png">

**Comment by clicman** [comment]
Also problem may in server encoding or smth

**Comment by dmitrii-slayer** [comment]
I see "Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8" in my terminal but it didn't help. 
I checked server logs and no problem with encoding in my requests, also no problem when I parse responses, so I don't think it's a server encoding issue. The problem is only with the logging

**Comment by dmitrii-slayer** [comment]
Found a solution - replaced StringBuilder with ByteArrayOutputStream in rest-plugin's ToLoggerPrintStream class - https://github.com/dmitrii-slayer/page-factory-2/commit/6b73f44d62965b1bd35a8fc9fc6ff6d36b15225e

**Comment by clicman** [comment]
@vserpokryl take a look please

**Comment by clicman** [comment]
Fixed in 17.1.0 (already available on central). @dmitrii-slayer check fix please and if it ok, close issue

**Comment by dmitrii-slayer** [comment]
Fixed. Thank you
