### ISSUE TITLE
Нельзя изменить декоратор

### ISSUE THREAD

**Issue by nstreltsov** [sbtqa/page-factory-2#390]
Добрый день.
У вас в коде прошит ваш декоратор, поэтому его изменить нельзя, хотя в справке написано что можно
CustomHtmlElementLoader#populatePageObject(Object page, CustomElementLocatorFactory locatorFactory)

Вернее можно, но получается кривой код и копипаста

**Comment by clicman** [comment]
Можно с примерами о чем речь?

**Comment by nstreltsov** [comment]
Допустим мне надо изменить только часть вашего декоратора, добавить новый тип, который допустим помечен какой-то аннотацией. Я наследуюсь от вашего декоратора `CustomHtmlElementDecorator` и переопределяю метод
`decorate(ClassLoader loader, Field field)`, в который добавляю новое условие для своего типа. Все хорошо, но когда используются "блоки" и код заходит в ваш метод `decorateHtmlElement(ClassLoader loader, Field field)`, который вызывает `populatePageObject(instance, elementToWrap)` то в нем создается новый инстанс именно вашего декоратора `PageFactory.initElements(new CustomElementDecorator(locatorFactory), page);`. 
Такое поведение можно изменить, если переопределить еще и decorateHtmlElement, куда скопировать все, что есть в нем у вас и скопировать метод `populatePageObject`, в который засунуть свой декоратор. Но на мой взгляд выглядит колхозно потому, что точка добавления декоратора - это PageObject класс, а тут получается в инициализации элементов опять надо добавлять новый инстанс того же декоратора.

**Comment by clicman** [comment]
Ок. Посмотрим

**Comment by nstreltsov** [comment]
спасибо

**Comment by kosteman** [comment]
Добрый день.
Правильно ли я понял, что вы экстендите `CustomHtmlElementDecorator` и затем используете его в своих PageObjects как `PageFactory.initElements(new NstreltsovCustomHtmlElementDecorator(locatorFactory), page);`?

Поясните, пожалуйста, что имеется в виду под 

> Все хорошо, но когда используются "блоки"

**Comment by nstreltsov** [comment]
Да, все верно, на счет расширения декоратора
Блоки https://sbtqa.github.io/?version=18.0.7#_%D0%91%D0%BB%D0%BE%D0%BA%D0%B8_%D0%B8_%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B когда есть блок, тогда в декораторе заходит сюда `decorateHtmlElement(ClassLoader loader, Field field)` и там ваш декоратор `PageFactory.initElements(new CustomElementDecorator(locatorFactory), page);`

**Comment by kosteman** [comment]
Насколько глобально необходимо задавать свой декоратор?
Ну то есть в каждом PageObject может использоваться свой декоратор или достаточно засетить свой кастомный декоратор при запуске проекта?
Все PageObject так или иначе наследуются от HTMLPage? Просто там тоже есть инит с нашим кастомным декоратором

**Comment by nstreltsov** [comment]
Один декоратор на все PageObject, у нас все классы со страницами наследуются от AbstractWebPage, который наследуется от HTMLPage
В конструкторе переопределяем декоратор
`
public AbstractWebPage(){
        super(new CustomElementDecorator(new HtmlElementLocatorFactory(Environment.getDriverService().getDriver())));
    }
`

**Comment by kosteman** [comment]
Добавил возможность указывать декоратор в application.properties, как использовать описано в доке. Это решение должно избавить от необходимости указывать свой декоратор в конструкторах PO, а также исправить поведение блоков.
Попробуйте использовать версию 18.1.0
