### ISSUE TITLE
Проблемы с загрузкой класса io.netty.bootstrap.Bootstrap

### ISSUE THREAD

**Issue by bostandyksoft** [sbtqa/page-factory-2#392]
Проект содержит транзитивные зависимости и с пакетами
io.netty:netty-all:4.0.51.Final и io.netty:netty-transport:4.1.87.Final

![image](https://github.com/sbtqa/page-factory-2/assets/4920442/97fe838c-89ff-4449-9253-56ce00c80f5a)

И в том, и в другом есть класс io.netty.bootstrap.Bootstrap разных версий, поэтому "успешность" запуска зависит от того, какой класс будет загружен Classloader.

При попытке выровнить версию io.netty:netty-all до 4.1.87 средствами Gradle ошибки создания Bootstrap не появляется, но websocket не может получить соединение к браузеру.

Есть идеи как это фиксить?

PS Посмотрел - в предыдущей версии транзитивные зависимости были только на netty-all, а не на кучу netty- пакетов.

**Comment by kosteman** [comment]
До 4.1.87 поднимали все пакеты или только netty-all?
Какой браузер?

**Comment by bostandyksoft** [comment]
Это дефолтный список, подгруженный Idea в проект example. Никаких манипуляций с зависимостями не проводил. В своем проекте поднял версию netty-all до версии 4.1.87 и добавил флаг --remote-allow-origins=* - заработало все

**Comment by clicman** [comment]
Fixed in https://github.com/sbtqa/page-factory-2/releases/tag/19.0.0
