### ISSUE TITLE
В page-factory-2 перестал работать запуск локального chromedriver

### ISSUE THREAD

**Issue by insomnia77** [sbtqa/page-factory-2#60]
Когда задаешь webdriver.drivers.path=src/test/resources/webdrivers/chromedriver.exe , то вылетает
btqa.tag.pagefactory.web.drivers.WebDriverService - Attempt 1 to start web driver
      java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html

В первой page-factory webdriver.drivers.path работает.

**Comment by ProsviryakovVadim** [comment]
Привет! Установи последнюю версию 2.0.2 и попробуй еще раз запустить.
Проверил только что, все работает. Обязательно напиши о своих результатах.

**Comment by clicman** [comment]
Долго нет реайции. закрываю
